In [1]:
#import necessary packages
import pandas as pd
import numpy as np
import torch


In [8]:
t1 = torch.tensor([1,1.3,5],dtype= torch.float32, device='cpu')
print(t1.dtype)

torch.float32


In [12]:
for i in range(6,9):
    print(i)

6
7
8


In [13]:
num1 = 3;
num2 = 9;

torch.tensor([i for i in range(num1,num2)])

tensor([3, 4, 5, 6, 7, 8])

In [18]:
t2 = torch.linspace(num1,num2,num2-num1)
print(t2, t2.requires_grad)

tensor([3.0000, 4.2000, 5.4000, 6.6000, 7.8000, 9.0000]) False


In [25]:
#t = torch.tensor([1,2,3])
#t = torch.tensor([[1],[2],[3]])
#t = torch.tensor([[1,2,3],[4,5,6]])
t = torch.tensor([[1,0,0],[0,1,0],[0,0,1]])
print(t)
print(t.shape, t.ndim)

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])
torch.Size([3, 3]) 2
