In [4]:
import torch

In [6]:
t = torch.rand(2,3,5)*5
print(t)

tensor([[[4.1855, 3.9086, 3.0418, 2.9450, 2.2175],
         [2.9989, 1.0791, 2.0601, 2.8603, 2.6973],
         [3.5623, 1.6531, 1.1320, 1.1530, 3.4365]],

        [[3.9606, 2.5906, 3.7646, 0.1959, 0.6207],
         [3.5155, 2.7587, 1.4519, 0.0115, 1.5869],
         [0.4452, 2.8573, 3.7101, 4.7041, 4.5867]]])


In [12]:
t1 = torch.floor(t)
print(t1)

tensor([[[4., 3., 3., 2., 2.],
         [2., 1., 2., 2., 2.],
         [3., 1., 1., 1., 3.]],

        [[3., 2., 3., 0., 0.],
         [3., 2., 1., 0., 1.],
         [0., 2., 3., 4., 4.]]])


In [13]:
t2 = torch.fix(t)
print(t2)

tensor([[[4., 3., 3., 2., 2.],
         [2., 1., 2., 2., 2.],
         [3., 1., 1., 1., 3.]],

        [[3., 2., 3., 0., 0.],
         [3., 2., 1., 0., 1.],
         [0., 2., 3., 4., 4.]]])


In [14]:
t3 = torch.round(t)
print(t3)

tensor([[[4., 4., 3., 3., 2.],
         [3., 1., 2., 3., 3.],
         [4., 2., 1., 1., 3.]],

        [[4., 3., 4., 0., 1.],
         [4., 3., 1., 0., 2.],
         [0., 3., 4., 5., 5.]]])


In [15]:
t4 = torch.ceil(t)
print(t4)

tensor([[[5., 4., 4., 3., 3.],
         [3., 2., 3., 3., 3.],
         [4., 2., 2., 2., 4.]],

        [[4., 3., 4., 1., 1.],
         [4., 3., 2., 1., 2.],
         [1., 3., 4., 5., 5.]]])
